version: '3'
services:
  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stocks?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@1234
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: stocks
      MYSQL_USER: root
      MYSQL_PASSWORD: root@1234
    ports:
      - "3306:3306"